version: "3.9"

services:
  backend:
    build:
      context: .
      target: backend
    container_name: desafio_backend
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    networks:
      - desafio_net

  frontend:
    build:
      context: .
      target: frontend
    container_name: desafio_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - desafio_net

networks:
  desafio_net:
    driver: bridge
